excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://karol93.github.io
title: .NET & JavaScript
email: karol.suchecki93@gmail.com
author: karol93
description: .NET & JavaScript
paginate: 5
google_analytics: 
